m={'柯南','灰原','步美','美環','光彦'}
e={'柯南','灰原','丸尾','野口','步美'}
a=m.intersection(e)
b=m.difference(a)
c=e.difference(a)
a1=list(a)
b1=list(b)
c1=list(c)
b1.sort()
print(b1)
c1.sort()
print(c1)
a1.sort()
print(a1)